#!/bin/bash
#
# This script handles actually running the server for the setup
# generated by ec2.sh: it starts the Sirikata server via God for
# montoring and starts the lighttpd server.

DIR=`pwd`

# Bail out with a message for the user
function bail {
    echo $1
    exit -1
}

# Check for required files
if [ ! -e be.git ]; then
    echo "Couldn't find kataspace code."
    exit -1
fi

if [ ! -e sirikata.git ]; then
    echo "Couldn't find sirikata code."
    exit -1
fi

# Run the main WSGI python server process
cd be.git && ./server/server.py &
cd ${DIR}

# Run lighttpd as the web server
cd be.git || bail "Couldn't find KataSpace code."
# lighttpd on Ubuntu starts itself automatically, so stop it first
sudo /etc/init.d/lighttpd stop
# Setup caching directory
sudo mkdir -p /tmp/lighttpdcompress || bail "Couldn't create lighttpd caching directory"
sudo chown root:root /tmp/lighttpdcompress || bail "Couldn't chown lighttpd caching directory"
# And then run our version
sudo ./contrib/lighttpd.py 80 /tmp/lighttpdcompress &
# Return to the top level directory
cd ${DIR}
